---

- include_tasks: package.yml
  when: >
    ansible_facts['os_family'] == 'Debian' or
    ansible_facts['os_family'] == 'RedHat'
  tags:
    - install
    - package

- include_tasks: homebrew.yml
  tags:
    - install
    - go

- include_tasks: github.yml
  tags:
    - install
    - github