---

- name: Update apt cache | package
  become: true
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install via Package Manager | package
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
    - vim
    - dos2unix
    - sipcalc
    - most
    - whois
    - screen
    - tmux
    - telnet
    - mc
    - amazon-ecr-credential-helper