---
# file: roles/zsh/tasks/main.yml

- name: Installs zsh | package
  become: true
  package:
    name:
      - zsh
      - git
      - wget
      - curl
    state: present

- name: Sets zsh as default shell for my user | command
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh

- name: Checks for oh-my-zsh installation | stat
  stat:
    path: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"
  register: oh_my_zsh_stat

- name: Installs oh-my-zsh | raw
  raw: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"'
  when: not oh_my_zsh_stat.stat.exists

- name: Links .zshrc file | file
  file:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: link
    force: yes

- name: Checkout powerlevel10k theme | git
  git:
    repo: https://github.com/romkatv/powerlevel10k
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: Links .p10k.zsh file | file
  file:
    src: "{{ role_path }}/files/p10k.zsh"
    dest: "{{ lookup('env', 'HOME') }}/.p10k.zsh"
    state: link
    force: yes